version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'makingSense'
      POSTGRES_PASSWORD: 'makingSense'
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data:
